name: Backend-deploy

on:
  push:
    branches: [ main,develop ]

  workflow_dispatch:

jobs:
  cicd:
    runs-on: ubuntu-latest
    environment: vms
    steps:
      - name: "⚡ Checkout"
        uses: actions/checkout@v3
      
      - name: "🧪 Setup node"
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          
      - name: "📦 Install Dependencies"
        working-directory: ./backend
        run: yarn install --frozen-lockfile
      
      - name: "🌹 Format Code"
        working-directory: ./backend
        run: yarn format
        
      - name: "🧶 Lint Code"
        working-directory: ./backend
        run: yarn lint
        
      - name: "🏁 Run tests backend"
        working-directory: ./backend
        run: yarn run test
        
      - name: "⭐️ Deploy backend container"  
        uses: gonuit/heroku-docker-deploy@v1.3.2
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile_directory: ./backend
          dockerfile_name: Dockerfile
          docker_options: "--no-cache"
          process_type: web
  
