# Development override for docker-compose
# This file is automatically loaded by docker-compose for development

version: '3.9'

services:
  backend:
    build:
      target: development
    environment:
      NODE_ENV: development
      LOG_LEVEL: debug
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev

  client:
    environment:
      NODE_ENV: development
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev

  data-prep:
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
    volumes:
      - ./data-prep:/app

  face-rec:
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
    volumes:
      - ./face-rec:/app

  mongodb:
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password